# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c619463a681f024574586c1cec461c4b9939e563805a6ea52e29ccefe6b3b183c501f2179278abb63bd4137e82bc73e4334cb0b23078fa6a534ca40be6b52ceb

test:
  secret_key_base: 18e00d5cf3151a67477b4354a82f4ce7181a8d48efe1a1b5a9f5929067d7a80c589c84b90c9dda06bff47ddddc9b48b5093660740e249a479adb75b7801f7812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
